Bump to k8s v1.29
openshift/cluster-kube-apiserver-operator pull request #1586
Opened 2023-11-22 11:35 UTC by sairameshv

cc: @soltysh

2023-11-28 11:44 UTC, soltysh requested changes

2023-11-28 11:44 UTC, soltysh commented on go.mod
> +go 1.21.3
Same as before go1.20

2023-11-29 07:12 UTC, sairameshv commented on go.mod
> +go 1.21.3
Addressed

2023-11-29 16:09 UTC, sairameshv commented
/retest

2023-12-18 15:43 UTC, soltysh approved these changes
/lgtm
/approve

2023-12-18 19:11 UTC, soltysh commented
/retest-required

2023-12-18 21:02 UTC, soltysh commented
/retest-required

2023-12-18 22:50 UTC, merged