OCPEDGE-902: add SNO control plane high cpu usage alert
openshift/cluster-kube-apiserver-operator pull request #1660
Opened 2024-04-03 17:45 UTC by qJkee

Create separate SNO alert for control plane high cpu usage. This alert is also aware of workload partitioning and adjusts threshold if workload partitioning is enabled.
I don't track performance profile because after applying new one, node restarts and I can recreate/update alert threshold with new cores amount

2024-04-18 09:19 UTC, vrutkovs requested changes
Looks good to me, cc @dgrisonnet for another pair of eyes

2024-04-18 09:19 UTC, vrutkovs commented on pkg/operator/starter.go
> +		WithConditionalResources(bindata.Asset, []string{"assets/alerts/cpu-utilization.yaml"}, notOnSingleReplicaTopology, nil).
Merge into previous line?

2024-04-18 15:23 UTC, dgrisonnet commented on bindata/assets/alerts/cpu-utilization-sno.yaml
> +            sum(rate(container_cpu_system_seconds_total{namespace=~"openshift-.*",image!=""}[5m])) / {{ . }} * 100 > 60
I believe that you should use `container_cpu_usage_seconds_total` as the `system` one will only account for time spend in the kernel space

2024-04-18 15:23 UTC, dgrisonnet commented on bindata/assets/alerts/cpu-utilization-sno.yaml
> +          for: 10m
For warning alerts, this should be 1h based on https://github.com/openshift/enhancements/blob/799dc3c7b974c35832daea4004b772a3c0102ee1/enhancements/monitoring/alerting-consistency.md#warning-alerts

2024-04-18 15:23 UTC, dgrisonnet commented on bindata/assets/alerts/cpu-utilization-sno.yaml
> +        - alert: ExtremelyHighIndividualControlPlaneCPU
I opened a separate PR to fix the HA alerts, but I am not a big fan of keeping both the warning and critical alerts here, as I detailed in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1555. IMO we should just keep the critical one around

2024-04-18 15:23 UTC, dgrisonnet commented on pkg/operator/workloadpartitioning/cpuPartitioningAlertRenderer.go
> +const defaultCoresNum = 4
Is it really safe to assume that all the SNO clusters that are running without CPU partitioning will have 4 cores? If we ever have a case where the machine has 2,6,8,.. cores, the alerts will become incorrect.

Maybe we could use `runtime.NumCPU()` from the go standard library to get an accurate value for the number of CPU available?

2024-04-23 18:01 UTC, dgrisonnet commented on bindata/assets/alerts/cpu-utilization-sno.yaml
> +          for: 1h
this is critical severity so we should have this down to like 10 minutes

2024-04-23 18:01 UTC, dgrisonnet commented on bindata/assets/alerts/cpu-utilization-sno.yaml
> +          for: 10m
I am still seeing a `for` clause set to 10 minutes when it should be 1h for warning alerts

2024-04-24 13:06 UTC, dgrisonnet commented on pkg/operator/workloadpartitioning/cpuPartitioningAlertRenderer.go
> +	return defaultCoresNum, nil
We might need to create a watcher logic that would update the alert whenever the workload partitioning values are updated no?

2024-04-24 13:07 UTC, dgrisonnet commented on pkg/operator/starter.go
> +	err = workloadpartitioning.CreateSNOAlert(ctx, dynamicClient, infrastructure.Status, controllerContext.EventRecorder)
We might need to create a watcher logic that would update the alert whenever the workload partitioning values are updated no?

2024-04-24 13:34 UTC, dgrisonnet approved these changes
/lgtm
/approve

2024-04-24 16:42 UTC, merged